# Generated by Django 6.1.1 on 2026-09-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lieu",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.ville",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.machine",
            ),
        ),
        migrations.AlterField(
            model_name="prixproduit",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.produit",
            ),
        ),
        migrations.AlterField(
            model_name="quantitemachine",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.machine",
            ),
        ),
        migrations.AlterField(
            model_name="quantiteproduit",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.produit",
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="arrivee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transports_arrivee",
                to="high_level.lieu",
            ),
        ),
        migrations.AlterField(
            model_name="transport",
            name="depart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transports_depart",
                to="high_level.lieu",
            ),
        ),
        migrations.AlterField(
            model_name="ville",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.pays",
            ),
        ),
    ]
