# Generated by Django 6.1.1 on 2026-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0002_alter_lieu_ville_alter_operation_machine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="quantite_produits",
            field=models.ManyToManyField(
                blank=True, null=True, to="high_level.quantiteproduit"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="operations",
            field=models.ManyToManyField(
                blank=True, null=True, to="high_level.operation"
            ),
        ),
    ]
