# Generated by Django 6.1.1 on 2026-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0003_alter_operation_quantite_produits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="quantite_produits",
            field=models.ManyToManyField(blank=True, to="high_level.quantiteproduit"),
        ),
        migrations.AlterField(
            model_name="pays",
            name="tarif_electrique",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="produit",
            name="operations",
            field=models.ManyToManyField(blank=True, to="high_level.operation"),
        ),
    ]
